### ISSUE TITLE
NVS error after 1st start

### ISSUE THREAD

**Issue by Nuts-Underline** [MathieuDeprez/my_esp32_watch_base#1]
Error afre 1st flashing
`Opening Non-Volatile Storage (NVS) handle... Error (ESP_ERR_NVS_NOT_FOUND) opening NVS handle!`
WatchNvs::init seraching storage stg_01 but the no such storage after 1st flashing
What  wrong with it?

**Comment by MathieuDeprez** [comment]
Hello,
The "ESP_ERR_NVS_NOT_FOUND" for the nvs_open() function means "id namespace doesn't exist yet and mode is NVS_READONLY" [doc_link](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/storage/nvs_flash.html)

If you change the opening mode of the nvs_open() (line 20), it will works :
```
//from
err = nvs_open(main_storage_name, NVS_READONLY, &my_handle);
//to
err = nvs_open(main_storage_name, NVS_READWRITE, &my_handle);
```
